### ISSUE TITLE
Support Resuming Existing Conversation

### ISSUE THREAD

**Issue by gerryfletch** [daan-dj/TurboGpt#2]
Since the current rate limit is 25 messages per 3 hours for GPT-4, spending an extra message on `start_session` is quite expensive. Could we remodel it to accept an optional `conversationId` (and maybe parent message id?) to resume an existing conversation? This would also help for resuming chats which have previously asserted rules and context for the model.

I'm running this in vscode tasks, so making it reuse an existing session isn't trivial.
As a side note, the library is working flawlessly for me and is super useful 🙏🏼  thanks!

**Comment by daan-dj** [comment]
great idea. I was already experimentiung with this locally. Will push the update tommorow or later tonight.

**Comment by gerryfletch** [comment]
Cool, happy to review any PRs or test anything! Just tag me :)

**Comment by daan-dj** [comment]
I think I can also depricate the starting message because the gpt4 and text-davinci-002-render-sha models already have this behavior when starting a new conversation with them. This saves messages for gpt4.

https://github.com/daan-dj/TurboGpt/blob/12445acc06044507bb3eeab0138d5b8ddb2cfb86/turbogpt/turbogpt.py#L60

**Comment by daan-dj** [comment]
merged @gerryfletch
